<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fn</string>
		<string>FN</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\#\#|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\#\#/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>Efene</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(after|switch|case|catch|else|fn|object|if|record|for|in|receive|try|when|and|andd|not|or|xor|orr)\b</string>
			<key>name</key>
			<string>keyword.control.ifene</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ifene</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.efene</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.efene</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.ifene</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.efene</string>
	<key>uuid</key>
	<string>F59FB659-AC59-4C5C-9B07-4891AEB55A62</string>
</dict>
</plist>
