au BufRead,BufNewFile *.fn, *.ifn set shiftwidth=4
au BufRead,BufNewFile *.fn, *.ifn set tabstop=4
au BufRead,BufNewFile *.fn, *.ifn source ~/.vim/syntax/efene.vim
au BufRead,BufNewFile *.fn, *.ifn set expandtab
au BufRead,BufNewFile *.fn, *.ifn match BadWhitespace /^\t\+/
au BufRead,BufNewFile *.fn, *.ifn match BadWhitespace /\s\+$/
au BufRead,BufNewFile *.fn, *.ifn set textwidth=79
au BufNewFile *.fn, *.ifn set fileformat=unix
