<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ifn</string>
		<string>IFN</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\#\#|\s*.*?=\s*fn\(.*?\)</string>
	<key>foldingStopMarker</key>
	<string>\#\#/|^\s*</string>
	<key>keyEquivalent</key>
	<string>^	</string>
	<key>name</key>
	<string>Ifene</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(after|switch|case|catch|else|fn|object|if|record|for|in|receive|try|when|and|andd|not|or|xor|orr)\b</string>
			<key>name</key>
			<string>keyword.control.ifene</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ifene</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ifene</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.ifene</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.symbol.begin.ifene</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.symbol.end.ifene</string>
				</dict>
			</dict>
			<key>name</key>
			<string>constant.other.symbol.quoted.single.ifene</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.ifene</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.escape.ifene</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\)([bdefnrstv\\'"]|(\^)[@-_]|[0-7]{1,3})</string>
					<key>name</key>
					<string>constant.other.symbol.escape.ifene</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\^?.?</string>
					<key>name</key>
					<string>invalid.illegal.atom.ifene</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(@)([a-z][a-zA-Z\d@_]*)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.begin.ifene</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.ifene</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.ifene</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))($)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>definition.parameters.end.ifene</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.ifene</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.ifene</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(@)([a-z][a-zA-Z\d@_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.begin.ifene</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.ifene</string>
				</dict>
			</dict>
			<key>end</key>
			<string>($)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.ifene</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.ifene</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.ifene</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.omitted.ifene</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(_[a-zA-Z\d@_]++|[A-Z][a-zA-Z\d@_]*+)|(_)</string>
			<key>name</key>
			<string>variable.other.ifene</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ifene</string>
	<key>uuid</key>
	<string>D97DA609-E685-4C8E-9F24-2B7CF42DBB32</string>
</dict>
</plist>
